# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170808_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 13, 22, 13, 179164, tzinfo=utc)),
        ),
    ]
